sudo: required
dist: trusty
before_install:
- sudo apt-get update
- sudo apt-get -y install texlive-full
- sudo tex -v
- sudo mkdir -p /usr/share/fonts/opentype/
- sudo mv ./guide-book/fonts/AdobeFangsongStd-Regular.otf /usr/share/fonts/opentype/
- sudo mv ./guide-book/fonts/AdobeHeitiStd-Regular\ \(v5.010\).otf /usr/share/fonts/opentype/
- sudo mv ./guide-book/fonts/AdobeKaitiStd-Regular\ \(v5.010\).otf /usr/share/fonts/opentype/
- sudo mv ./guide-book/fonts/AdobeSongStd-Light\ \(v5.010\).otf /usr/share/fonts/opentype/
- sudo mkfontscale
- sudo mkfontdir
- sudo fc-cache -fv
- fc-list :lang=zh
- sudo wget http://mirrors.ctan.org/macros/latex/contrib/minted.zip
- sudo unzip minted.zip
- cd minted/
- sudo make
- sudo mv minted.sty /usr/share/texlive/texmf-dist/tex/latex/minted
- sudo mv minted1.sty /usr/share/texlive/texmf-dist/tex/latex/minted
- cd ..
- sudo apt-get install python-pygments
script:
- cd guide-book
- make
- ls
- cd ..
- ls
deploy:
  all_branches: true
  provider: releases
  api_key:
    secure: Yi/f3naw7C5RbnEdSw1UGg3hxhnbx//oE1gSBB+XOx24Fk+53PKqeu0SWj5VDZhhdu9YF2dof+TLiatwvE6ycbSj8O5LGKbr5aGymaPLjaiqBpmRzU3PG8SJ3Zv16agzCQVlwICHHjLY2vc2r4mnIILhHeVSepwMgMJc1W5b1zn2Z3ItnPsjLlP7gwetVXVuXribGVbR2DvuDcE6sbBEC+lUerx4haVCCcnewemw8gaCChwoGzHxxy8RPiySYifhK9cpuEGln3cWT57taLiLSbEqxrLBWsQ8+SPKUGWeduhkuexTosG7w1vemIMoe+/y6o0cn/p4JIJ8F9MpYHCZjQpn3ywE56eH0t+R38zwl1typQAD/x9Y6riFZdEYuvxkqrWF6VRQG8LYPq2pRLAWmYXZNuOScrV2vR3Loa3IKEKUxjdNDmB1kHVIKhiCt4HSwCdVXdbSZTyqWBpPS35p3n86nKF8Oi/JpudspFOIESsAWKWyaOVZfvgzQG8eZJWRQvwMQh1Gbc5XM+BQDuoG/SDti+088T0az3OGnaJsCNGPG1fvL0q3TCjKACtqEz89jA3BiWiewKg5kgD+t0KpSpNdy8rVGG5M+o8XUHUBfYvuHDVWJlN6RsaOmbAcWnVCQotjX9evWd8q2S2RTRgEJLWAa1aTVj+8X2iSWCkSw6Y=
  file: guide-book/guide-book.pdf
  on:
    repo: oncebasun/BUAAOS-guide-book
